version: '3.1'

services:
  springboot:
    image: praveen514/spring-boot-mongo:1
    restart: always # This will be ignored if we deploy in docker swarm
    ports:
      - 9090:8080
    depends_on:
      - mongo
    networks:
    - springappnetwork

  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
    - springappnetwork
    
volumes:
  mongodb:
    driver: local
    
networks:
  springappnetwork:
    driver: bridge
